### ISSUE TITLE
切换其他城市后天气图标不显示

### ISSUE THREAD

**Issue by fuxuemingzhu** [xcc3641/SeeWeather#10]
不知道是因为切换的问题，还是因为切换后的城市的天气没有图标。这个问题有时会出现，有时没有。

**Comment by xcc3641** [comment]
能告知是什么城市吗？

**Comment by fuxuemingzhu** [comment]
比如 **台**￥￥%*…# **湾**……@#5%**高**￥￥W#**雄**
