### ISSUE TITLE
请问下你的weather实体类是用工具生成的吗

### ISSUE THREAD

**Issue by ixnyu** [xcc3641/SeeWeather#16]
用http://www.jsonschema2pojo.org/ 在线生成的会拆分多个类,你是自己组合成一个类的吗
用GsonFormat生成的没有注解

**Comment by xcc3641** [comment]
就是那个工具~ 改下设置就行了，可以加注解。

**Comment by ixnyu** [comment]
哦  谢谢 我设置了注解但是只要几个属性有 不像你的所有属性都有注解
