### ISSUE TITLE
 error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.

### ISSUE THREAD

**Issue by Pangz1992** [xcc3641/SeeWeather#17]
求解答，把android-support-v4.jar，android-support-v7-appcompat.jar导进去了，还是报错。

**Comment by xcc3641** [comment]
<style name="AppBaseTheme" parent="android:Theme.Light">

改成这样呢？

Pangz1992 <notifications@github.com>于2016年4月21日周四 上午9:21写道：

**Comment by Pangz1992** [comment]
这个之前试过，然后报错：error ：no resource found that mathches the given name :attr'colorAccent'还有'colorPrimary' 和'colorPrimaryDark'      - -!

**Comment by xcc3641** [comment]
你更新下 兼容包吧 都保持最新的。

Pangz1992 <notifications@github.com>于2016年4月21日周四 下午2:34写道：
