### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by rayeaster** [xcc3641/SeeWeather#18]
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by ixnyu** [comment]
相同的问题

**Comment by ixnyu** [comment]
相同的问题

**Comment by xcc3641** [comment]
再 pull 下代码试试 @ixnyu @rayeaster

**Comment by ixnyu** [comment]
你最小支持版本是 19 我改成 15 运行在 18版本上报的这个异常

**Comment by xcc3641** [comment]
我已经抛弃了 19以下的用户，你需要兼容的话，自己试试吧~

ixnyu <notifications@github.com>于2016年4月22日周五 下午7:56写道：

**Comment by ixnyu** [comment]
放弃 4.0以下我能理解 4.4以下用户还是挺多理解不了
我就是想支持4.0以上 看样子是支持不了

**Comment by ixnyu** [comment]
你都没办法 我也搞不定
