### ISSUE TITLE
WeatherAdapter.java中onBindViewHolder方法改成这样写是否会更优雅

### ISSUE THREAD

**Issue by zhushi91** [xcc3641/SeeWeather#22]
@Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position) {
        int itemType = getItemViewType(position);
        switch (itemType) {
            case TYPE_ONE:
                break;

            case TYPE_TWO:
                break;

            case TYPE_THREE:
                break;

            case TYPE_FORE:
                break;
        }
        showItemAnim(holder.itemView, position);
    }

**Comment by xcc3641** [comment]
收到建议~谢谢
