### ISSUE TITLE
数据显示不出来

### ISSUE THREAD

**Issue by 329377653** [xcc3641/SeeWeather#24]
hello，选择城市后数据显示不出来 url如下
https://api.heweather.com/x3/weather?city=%E5%A4%A9%E6%B4%A5%E5%B8%82&key=282f3846df6b41178e4a2218ae083ea7

如果把天津市 换成天津就可以了

**Comment by xcc3641** [comment]
= = 我是做了这个处理的啊。
	
    /**
     * 正则匹配掉错误信息
     */
    public static String replaceCity(String city) {
        city = safeText(city).replaceAll("(?:省|市|自治区|特别行政区|地区|盟)", "");
        return city;
    }

**Comment by 329377653** [comment]
sorry  是我把那个注掉了
//        String cityName = Util.replaceCity(mSetting.getCityName());
        String cityName = mSetting.getCityName();
是如果用上面那个方法，city会为空
https://api.heweather.com/x3/weather?city=&key=282f3846df6b41178e4a2218ae083ea7

**Comment by xcc3641** [comment]
看你改了什么东西吧，我这里一直都没有问题。

**Comment by 329377653** [comment]
Util.class    
是因为这一句 注释掉就可以了，本地项目有这句吗？  github上的项目是有的
public static String safeText(String prefix, String obj) {
//        if (TextUtils.isEmpty(obj)) return "";
        return TextUtils.concat(prefix, obj).toString();
    }

**Comment by xcc3641** [comment]
有的，因为要用这个判断 传入的是否是 null 啊。不然会崩溃的。

**Comment by 329377653** [comment]
public static String safeText(String msg) {
        return safeText(msg, "");
    }
因为上面调用的时候传了一个空的字符串，所以到public static String safeText(String prefix, String obj) 
这个方法就会直接返回空了，所以city为空

**Comment by 329377653** [comment]
额 是的 不知道你还有没用到 
    public static String safeText(String msg) {
        return safeText(msg, "");
    }
这个方法 只有一个参数的

**Comment by xcc3641** [comment]
= = 噢，是因为这里没有更新到。本地我换了参数位置。sorry

**Comment by xcc3641** [comment]
不对。我线上代码是对的。你应该没有 pull 更新。
	
    /**
     * 安全的 String 返回
     *
     * @param prefix 默认字段
     * @param obj 拼接字段 (需检查)
     */
    public static String safeText(String prefix, String obj) {
        if (TextUtils.isEmpty(obj)) return "";
        return TextUtils.concat(prefix, obj).toString();
    }

    public static String safeText(String msg) {
        return safeText("", msg);
    }

**Comment by 329377653** [comment]
好像是前天 Clone下来就没更新过了。。  好的 谢谢
