### ISSUE TITLE
博客里说的方法这里怎么没有？

### ISSUE THREAD

**Issue by chaozaiai** [xcc3641/SeeWeather#25]
public static <T> Observable.Transformer<Result<T>, T> handleResult() {
    return resultObservable -> resultObservable.flatMap(tResult -> {
        if (tResult.code == 1) {
            return createData(tResult.data);
        } else {
            return Observable.error(new ApiException(tResult.code));
        }
    });
}

**Comment by xcc3641** [comment]
因为 和风天气 API 不是 restful ，这个是用在团队项目里的，在天气这里没有用到这个。

**Comment by chaozaiai** [comment]
赞一个

**Comment by chaozaiai** [comment]
嗯，
