### ISSUE TITLE
有这个firebase就构建出错

### ISSUE THREAD

**Issue by focus2846** [xcc3641/SeeWeather#28]
Error:(91, 13) Failed to resolve: com.google.firebase:firebase-core:9.0.0
<a href="openFile:C:/Users/Fancy_wu/Desktop/SeeWeather-master/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by LewZ** [comment]
下载sdk manager中extra里面的Google play service 还是 google repository就能解决这个问题
