### ISSUE TITLE
关于CollapsingToolbarLayout

### ISSUE THREAD

**Issue by SmallCXL** [xcc3641/SeeWeather#29]
请问一下作者，怎么设置这个控件在创建的时候保持在Collapsed状态？我看你之前的代码中有这个设置，但是后来你改了主界面，就没用这个控件了，能否告知一下那个方法？多谢~~

**Comment by xcc3641** [comment]
具体的是在 AppBarLayout 里设置 Collapsed 状态。

**Comment by xcc3641** [comment]
AppBarLayout
setExpanded(boolean)

**Comment by SmallCXL** [comment]
非常感谢~~我最近在自学安卓编程，遇到许多问题都能从你的demo中找到解决方案，特别是从你的博客中了解到许多关于rxjava的东西，很受用，感谢作者！

**Comment by xcc3641** [comment]
@SmallCXL 
没事，相互学习嘛~
