### ISSUE TITLE
关于主页面，顶部状态栏白色。

### ISSUE THREAD

**Issue by jiandaima** [xcc3641/SeeWeather#3]
关于主页面，顶部状态栏白色。
如图。。
![screenshot_2016-02-22-14-51-06_com xiecc seeweath](https://cloud.githubusercontent.com/assets/15846634/13211508/d7a2c13a-d973-11e5-8592-1cf63b65c8c6.png)
![screenshot_2016-02-22-14-51-10_com xiecc seeweath](https://cloud.githubusercontent.com/assets/15846634/13211509/d85712de-d973-11e5-842f-ddbe4e79dc71.png)
机型为红米1s：
![screenshot_2016-02-22-14-53-21_com android settin](https://cloud.githubusercontent.com/assets/15846634/13211543/17679a66-d974-11e5-9d98-28be78067b12.png)

**Comment by xcc3641** [comment]
嗯嗯 收到，我下个版本适配下5.0以下的状态栏。

**Comment by wuchangfeng** [comment]
您好，调试你的代码学习。发现页面出不来数据，是要替换天气或者地图的key吗？另外，提个小建议，可以根据当天的天气，切换主界面上方图片);

**Comment by xcc3641** [comment]
@wuchangfeng 嗯，我在README里面写了的，运行源代码需要去申请天气key。收到你的建议，这个需要做一套图才行，需要花时间。

**Comment by tianshaokai** [comment]
有时候提示http401unauthorized

**Comment by wuchangfeng** [comment]
十分抱歉，刚才读了一下readme发现了。点个赞，就用你的应用学习Rx系列了，嘿嘿。

**Comment by xcc3641** [comment]
@tianshaokai 我把天气的key和高德地图的key都删掉了。所以才会有这个错误。

**Comment by xcc3641** [comment]
@wuchangfeng 加油，有任何改进和建议尽管提出来。

**Comment by ggggxiaolong** [comment]
http://www.jianshu.com/p/0acc12c29c1b
一个简单的解决办法
