### ISSUE TITLE
高德定位无法获取定位结果

### ISSUE THREAD

**Issue by williamwue** [xcc3641/SeeWeather#30]
小米Note，Android 6.0系统，已开启定位等App权限，启动会显示"定位失败，加载默认城市"

**Comment by xcc3641** [comment]
请问你是开发者版本吗？还是正式版本？
开发者版本的高德地图 key 是无法定位的
只有正式发布版本。

**Comment by williamwue** [comment]
明白了，应该是这个原因，我是用的开发版本
