### ISSUE TITLE
反馈一个测试使用中发现的小bug

### ISSUE THREAD

**Issue by SmallCXL** [xcc3641/SeeWeather#33]
楼主你好，我最近在开发相似的一款软件，同时也在帮你测试，发现有点小bug，这个bug在我自己的项目中也出现过。就是在你的ChooseCityActivity中，没有对queryCities这个方法做容错处理，当选择的城市是一个和风天气api没有的城市时，导致以下bug：
1）若当前为多城市模式，即isChecked = true，直接闪退。
2）当前不是多城市模式，虽然会提示网络不好（个人认为要提示没有这个城市信息更合理），但是主界面的下拉刷新动画会一直存在，并且此时再往下拖动主界面的时候，也会闪退。
这两个bug应该都是空指针的报错。建议在queryCities这个方法中，加上一个完整的Subscriber，处理好onError事件，并在queryCities方法中，加上.doOnTerminate(() -> mProgressBar.setVisibility(View.GONE))。以上为个人意见，欢迎讨论。P.S：你的支付宝账号好像有问题，加不了。。。

**Comment by SmallCXL** [comment]
上面说的不存在的城市，你可以选择内蒙古的“锡林郭勒盟”来测试

**Comment by xcc3641** [comment]
噢噢 谢谢  我马上加上改下
支付宝我手贱加了隐私 233

SmallCXL <notifications@github.com>于2016年8月5日周五 下午12:38写道：

**Comment by xcc3641** [comment]
谢谢谢谢~
支付宝我手贱加了隐私
