### ISSUE TITLE
闪退问题还是存在。。

### ISSUE THREAD

**Issue by aer874475222** [xcc3641/SeeWeather#35]
闪退问题还是存在，我oppo安装4.4版。。

**Comment by xcc3641** [comment]
能给我看看日志吗？在 /data/androidcom.xiecc.seeweather 包下有个 log.txt 日志

**Comment by aer874475222** [comment]
没有啊 ，只有cache文件夹 里面也是空的

**Comment by xcc3641** [comment]
= = 好奇怪。你是 debug 还是发布的版本？

**Comment by aer874475222** [comment]
发布的版本

**Comment by xcc3641** [comment]
[2.2.2](http://fir.im/seeWeather?release_id=57b083d1ca87a82d4f000ffd)
能麻烦你试试这个版本吗？

**Comment by aer874475222** [comment]
还是一样啊。。。安装完成后，打开停1、2秒直接崩溃

**Comment by xcc3641** [comment]
可以加个联系方式吗？ qq 446022570
