### ISSUE TITLE
温度和风速单位表示建议

### ISSUE THREAD

**Issue by yuht** [xcc3641/SeeWeather#37]
温度用℃表示可能应该会比用°表示要好吧。
还有风速用Km/h表示才是正确的。Km表示的是距离。

**Comment by xcc3641** [comment]
收到

**Comment by yuht** [comment]
我不懂java的构架，所以无法帮助您完成修正。
您辛苦了

**Comment by xcc3641** [comment]
这个修改很简单，我下一个版本更新，为了一个小的修改发新版本不太好( •̥́ ˍ •̀ू )
有任何意见都可以提😊

2016年8月19日 08:02，"yuht" <notifications@github.com>写道：

**Comment by yuht** [comment]
values/styles.xml文件提示未找到变量定义
![values-styles](https://cloud.githubusercontent.com/assets/749642/17797395/244d6418-65fb-11e6-941e-f50ce0a335c0.png) 


values-v21/styles.xml文件提示未找到变量定义
![valuses-v21-styles](https://cloud.githubusercontent.com/assets/749642/17797375/fb47048e-65fa-11e6-9f81-f8a7b036a42a.png)

**Comment by xcc3641** [comment]
你这是 eclipse ？
你用 Android Studio 打开吧。

**Comment by yuht** [comment]
Android Developer Tools

![adt](https://cloud.githubusercontent.com/assets/749642/17797619/e8a391d8-65fc-11e6-9d66-7e79c558db3a.png)

**Comment by yuht** [comment]
adt version

![adt ver](https://cloud.githubusercontent.com/assets/749642/17797671/56cb1816-65fd-11e6-8a43-513ca665ee6e.png)
