### ISSUE TITLE
关于数据缓存的问题和一个bug

### ISSUE THREAD

**Issue by whyalwaysmea** [xcc3641/SeeWeather#39]
我看你是使用了OkHttp的缓存，但是在断网的状态下依然是不会显示数据的，请问这是为什么呢？
还有一个bug是，在断网状态下进入app，然后再连接上网络，没法刷新也就没法获取数据了

**Comment by xcc3641** [comment]
hi
1. 第一个问题，断网后我测试是缓存成功，并且显示了数据的。
请检查下你是否最新的代码或者软件版本。

2. 第二问题是我自己的问题。

**Comment by whyalwaysmea** [comment]
嗯，我再次测试了缓存，在真机上是成功了的，在模拟器上失败了？
想请求一下关于OkHttp缓存的问题，使用okhttp直接做缓存是不是需要服务器端做响应的支持呢？ 我用了一下豆瓣的接口，在没网的时候总是返回504

**Comment by xcc3641** [comment]
服务器不支持的话 我们可以做一个拦截器 Respose 修改头部信息，让 okhttp 支持缓存

**Comment by whyalwaysmea** [comment]
嗯，我看了你的代码，你应该是设置了拦截器的了吧。我按照你的做法，自己测试了一下，有了缓存文件，但是在没有网络的时候就还是不行。
再请教一下你认为什么时候该用okhttp缓存，什么时候用文件或者数据库来缓存请求回来的数据呢

**Comment by xcc3641** [comment]
看你需求吧。
这个根据业务来和具体场景才好说。
