### ISSUE TITLE
沉浸式状态栏

### ISSUE THREAD

**Issue by maxpreston** [xcc3641/SeeWeather#42]
刚开始接触响应式编程，就看到了你的项目，做的很不错，但是看了源码有一处沉浸式状态栏的设置，个人感觉项目中的沉浸式状态栏并没有达到真正的沉浸式，而是一种透明状态栏的效果.个人观点，希望互相学习。

**Comment by xcc3641** [comment]
嗯，国内最近一直都在讨论这个问题。
我只是按照规范用的系统的设计概念。
