### ISSUE TITLE
在FirstActivity没有调用setContentView方法

### ISSUE THREAD

**Issue by GeekTR** [xcc3641/SeeWeather#43]
感觉这种写法并不是很好

**Comment by xcc3641** [comment]
你说说哪点不好了诶。

**Comment by xcc3641** [comment]
因为对于引导页还没有新的想法，所以是用的一张图片。
然后我是直接给该 Activity 设置全屏主题图片。这样在启动 App 的时候不会出现白框。

**Comment by GeekTR** [comment]
白边？你是说状态栏那个白边吗？全屏主题就不会存在那个白边啊。

**Comment by xcc3641** [comment]
不是说状态栏。
这是以前观察出来的。
> 很多应用打开的时候，会整个白色/黑色 —-> 闪屏页。
future 想做一个简单动画和判断逻辑。现在只是这样过渡，当然这样写我还不知道你说的哪点不好。

**Comment by GeekTR** [comment]
这样写会导致通过这个activity的context show出来的Toast和Dialog都默认带这个背景，不过你这样写白边出现的时间确实少很多。
**还有我觉得FirstActivity里面Handler中handlerMessage中的代码改为这样比较好一点

> FirstActivity firstActivity = mWeakReference.get();
            if(null != firstActivity){
                Intent i = new Intent(firstActivity, MainActivity.class);
                firstActivity.startActivity(i);
                //activity切换的淡入淡出效果
                overridePendingTransition(android.R.anim.fade_in, android.R.anim.fade_out);
                firstActivity.finish();
            }

同时将SwitchHandler改为静态类，这样不容易内存泄漏

**Comment by xcc3641** [comment]
我 handler 是对 Activity 弱引用的啊 = =

**Comment by GeekTR** [comment]
非静态内部类对外部类会默认持有一个强引用，不然你怎么可以使用FirstActivity.this呢？

**Comment by xcc3641** [comment]
好像是我的问题。当初是想学使用弱引用来写 handler 。
看到了这篇，看来姿势错误。
- [How to Leak a Context: Handlers & Inner Classes](http://www.androiddesignpatterns.com/2013/01/inner-class-handler-memory-leak.html)
谢谢。
