### ISSUE TITLE
Wish

### ISSUE THREAD

**Issue by WengHaobin** [xcc3641/SeeWeather#45]
提议：要是能有桌面的天气小部件就更好了(笑着哭)

**Comment by xcc3641** [comment]
一直没有好的灵感写小部件布局。现在都是大同小异的。所以就一直空着没有写。

**Comment by WengHaobin** [comment]
市场里是有很多天气小部件，但是都不合我心意，就看天气实在是很棒，简洁好看，我和酷友们都期待你的小部件！加油！

**Comment by xcc3641** [comment]
感恩。
