### ISSUE TITLE
记录用户反馈

### ISSUE THREAD

**Issue by xcc3641** [xcc3641/SeeWeather#5]
## 城市列表
- ~~卡顿（progress dialog之后显示出数据库结果）~~
-  ~~点击省份后标题栏显示省份信息~~
- 加入搜索

**Comment by xcc3641** [comment]
## 首页
- 捕获网络异常
- 进度条过渡

**Comment by ycdm** [comment]
.idea这个文件夹是不是不需要上传

**Comment by xcc3641** [comment]
@ycdm 刚刚查了下，是的。我没有注意到这个。

**Comment by ggggxiaolong** [comment]
如果不上传的话 我的as会有错误的 版本2.0beta6

**Comment by tianshaokai** [comment]
.idea 你导入的时候studio 会自动创建的，所以不用上传

**Comment by ggggxiaolong** [comment]
@tianshaokai 你说的对
