### ISSUE TITLE
Rxjava初学疑问：doOnError不是在上游线程里执行的吗？

### ISSUE THREAD

**Issue by CCY0122** [xcc3641/SeeWeather#58]
我有个疑问，doOnError难道不是在`subscribeOn`所指定的线程里被调用的吗？
作者项目中在 `RetrofitSingleton.fetchWeather(String city)`方法里面的`doOnError`调用了`disposeFailureInfo`，该方法里涉及了UI操作，可是它的`subscribeOn`指定的是IO线程，为什么不会有错呢？

**Comment by xcc3641** [comment]
可以建议你看看这篇文章 [RxJava 线程切换源码的一些体会和思考](http://imxie.itscoder.com/2016/12/25/how_the_rxjava_thread_work/)

**Comment by CCY0122** [comment]
自己做了些测试，是我对doOnXXX系列理解错了
