### ISSUE TITLE
HTTP401 Unauthorized 问题请看该ISSUES

### ISSUE THREAD

**Issue by xcc3641** [xcc3641/SeeWeather#7]
就看天气是开源项目同时也是上线项目，所以为了用户的使用，我删掉了自己用的和风天气和fir的key

大家要pull下来编译，需要大家自己申请key，并且写在Setting里。

**Comment by chenyummy** [comment]
恩，我加入了Key，可以正常使用，但会出现一个401Toast

**Comment by xcc3641** [comment]
那就只有fir的检查软件版本的key的问题了。不过那个你可以删掉的，没有影响。

**Comment by cuikangyuan** [comment]
具体setting 应该写在哪里呢？没有找到位置呀

**Comment by cuikangyuan** [comment]
@chenyummy 请问 key 添加的具体位置是？setting是指？
