### ISSUE TITLE
View can not be anchored to the the parent CoordinatorLayout

### ISSUE THREAD

**Issue by ChoicesWang** [xcc3641/SeeWeather#9]
a bug in support lib 23.2.0。FloatingActionButton can't anchor to CoordinatorLayout。

**Comment by ggggxiaolong** [comment]
我之前也遇到了这个问题 这是我的代码（其实是谷歌的，更新lib之后新建一个工程就是这个代码）
<android.support.design.widget.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="bottom|end"
            android:layout_margin="@dimen/fab_margin"
            android:src="@drawable/ic_favorite_24dp" />

**Comment by xcc3641** [comment]
@ggggxiaolong 意思是
```app:layout_anchor=""  app:layout_anchorGravity="end|bottom"```
最新的库里不用了？

**Comment by ggggxiaolong** [comment]
是的，使用 23.2会报错 
需要设置成app:layout_anchorGravity="end|bottom"

**Comment by xcc3641** [comment]
@ggggxiaolong 好的 谢谢
